### ISSUE TITLE
Enhance/refactor HTTP structs for more robust modeling

### ISSUE THREAD

**Issue by autodidaddict** [wascc/wascc-codec#10]
The HTTP request and response structures could use a bit of improving.

* HTTP Request and Response use a simple `HashMap<String, String>` to represent HTTP headers. I think should be improved a bit since this is an over-simplification of the real data structure for HTTP headers. This should map more closely to what real HTTP libraries (like `reqwest`) expect and generate.

* The `path` field on the `Request` structure is used two different ways, depending on the direction of data. If an HTTP server is submitting a request to an actor, the `path` field contains nothing but the path - no host name, no port, no scheme. This `path` field holds a fully qualified URL when a request is being submitted to the capability provider for fulfillment. We should probably modify this field to better indicate this behavior, maybe call it `location` and have it be an enum with either a `URL` variant or a `Path` variant.

**Comment by ewbankkit** [comment]
Maybe get some inspiration from https://github.com/hyperium/http? I've seen that crate used in various other HTTP-focused scenarios.

**Comment by protochron** [comment]
`reqwest` actually just depends on the types exposed by https://github.com/hyperium/http: https://github.com/seanmonstar/reqwest/blob/master/src/lib.rs#L208-L211. We could just leverage the `http` crate and avoid reinventing the wheel if that makes sense.

Instead of storing a field called `path` could we store a URI and enforce the authority (if present) being `http(s)` or a single path? An Enum could work as long as it doesn't end up being more complicated than handling a URI to begin with

**Comment by autodidaddict** [comment]
I like the `http` crate, my only concern is that crate is 102kb, and every actor and capability provider in the waSCC ecosystem depends directly or transitively on the wascc-codec crate. I'm assuming that types not used by the consumers would be optimized out of the release binaries?

If that's the case, since the http crate types are already marked as serializable, they can be marshaled via waSCC's messagepack serializer and the `http` module could just re-publish the types from the http crate.

Thoughts on the consequences of doing this, if any? @protochron @ewbankkit

**Comment by ewbankkit** [comment]
What about the experience for actors that aren't implemented in Rust; Is describing the structures declared in `http` too onerous for the Assembly Script SDK for example?

**Comment by autodidaddict** [comment]
This would really create a burden on the assemblyscript SDK. Also, I've done some initial testing and it looks like the `http` crate doesn't have enough generic implementations to automatically infer that `Request<T>` is serializable (it doesn't require that T also be serializable). So, re-exporting the HTTP crate isn't going to work anyway.

This is an excellent point, @ewbankkit - any changes we make to the wascc-codec need to be ones that we can represent in WIDL and in turn be generate-friendly in the AS tooling.

**Comment by protochron** [comment]
Ah, good call. I was mostly thinking about Rust actors and not other kinds. It sounds like not depending on the `http` crate and implementing a type specific to the codec makes more sense then.

**Comment by autodidaddict** [comment]
It looks like we might be able to model the raw data structure as a map of multiple values, where each key is a string (the header name) and the values are all just blobs , and then it's up to the library to determine how to treat each blob. we can copy over the constants that represent the standard headers. 

@pkedy do you have any thoughts on how we might better represent an HTTP header and the path (with optional scheme and port) in [WIDL](https://github.com/wapc/as-codegen)?

**Comment by pkedy** [comment]
@autodidaddict Are you trying to support names with multiple values?  See below.

```
type Request {
  headers: [HeaderValue]  // Option 1
  headers: {string, [string]}  // Option 2
}

type HeaderValue {
  name: string
  value: string
}
```

For path/URL you could break the pieces into individual fields.
