### ISSUE TITLE
Capability providers should expose interface descriptors

### ISSUE THREAD

**Issue by autodidaddict** [wascc/wascc-codec#11]
Given any capability provider on the current version of the codec/conforming to the current mandatory trait, we can glean the following information:

* The capability ID
* A friendly (user-facing) description of the capability provider. Documentation indicates it's best practice to include which specific product/capability this provider connects to (e.g. include the word NATS or RabbitMQ or Kafka for those respective providers)

What we don't know is which operations the provider expects to be called by actors and which operations the capability provider expects to invoke on actors. There are two mandatory operations for capability providers:

* `OP_BIND_ACTOR` - bind a set of configuration values to a given named binding of this provider
* `OP_REMOVE_ACTOR` - dispose of any resources belonging to the bindings for an actor

Beyond this, the interface pattern is as opaque as the potential payloads the provider and actors may share.

I'd like to propose that in addition to the mandatory methods (will be constants as of #8 ) also include a mandatory constant that exposes a set of _operation descriptors_.

An **operation descriptor** should contain:
* The name of the operation (e.g. `DeliverMessage` or `HandleRequest` or `PerformRequest`)
* The direction/mode of the operation invocation allowed by this provider (can be `ToActor`, `ToProvider`, or `Both`)
* A human-readable documentation-style string that can be used by tools examining dynamically loaded plugins.

~A short-hand, machine-parseable format for an operation descriptor is discussed in wascap #22~.

_All_ capability providers would be required to expose this functionality, including _portable capability providers_, which would mean that the provider's WASI module would have to support a meta-operation that requests the list of operation descriptors (making an operation like `OP_LIST_DESCRIPTORS` mandatory for portable providers).

**Comment by ewbankkit** [comment]
Does the **operation descriptor** need a version so that it can evolve over time?

**Comment by autodidaddict** [comment]
The contract with a capability provider is, at this point, bound to the provider's version. With 1st party providers, that contract comes from `wascc-codec`, which is the sum of all first-party provider operations. With 3rd party providers, that usually ends up in a shared crate between the provider and the consuming actors.

Put another way, we're not versioning individual operations, but rather the entire suite of operations. If we are going to expose the descriptors, we probably should get the providers to expose their version number as well.

**Comment by autodidaddict** [comment]
Portable capability providers (WASI `wasm` modules) already have a version and revision fields as part of their token, so native capability providers not exposing a function/constant for the version seems like an oversight rather than a feature to be added ;)

**Comment by ewbankkit** [comment]
`In`, `Out`, `InOut` seem like more "standard" names for the directions - Is there any obvious mapping of these to the suggested directions?

**Comment by autodidaddict** [comment]
The problem with `In` and `Out` is that it is confusing with regard to relativity. If the operation is an `In` operation, is that in relative to the actor, or relative to the provider? While it might be obvious to some that it should be relative to one versus the other, I'd rather not open the door for a recurring source of confusion and keep things explicit.

I'm open to better names, but I want to avoid leaving it as an exercise to the reader to determine which is the default relative direction.

**Comment by ewbankkit** [comment]
Makes sense.

**Comment by ewbankkit** [comment]
Are native and portable capability providers similar enough that it's worth considering using `OP_LIST_DESCRIPTORS` as the discovery mechanism for both?

**Comment by autodidaddict** [comment]
That's an excellent point @ewbankkit , `OP_GET_CAPABILITY_DESCRIPTOR` should be something that all capability providers need to respond to, either native or portable ... making one more required operation isn't that bad in the name of consistency and more forward thinking (banking on the idea that one day WASI will be mature enough so that all our cap providers can be written as privileged actors).

**Comment by autodidaddict** [comment]
I was originally thinking that this idea would make it so that I would have to revoke a dispatcher in the case of a provider that couldn't be executed, but we don't actually check permissions until the time of binding, which is after the dispatcher has been configured, so that'll all still work nicely.
