### ISSUE TITLE
Why is `CapabilityProvider::name` a method instead of an associated constant?

### ISSUE THREAD

**Issue by rylev** [wascc/wascc-codec#8]
It would seem to make more sense for there to be a `CapabilityProvider::NAME` associated constant rather than a method. Why was the method chosen and not the associated constant?

**Comment by autodidaddict** [comment]
Because you can't invoke an associated type from an FFI instance. Capability providers need to be able to be dynamically loaded from library files... And so we create an instance of the provider and cast it to the provider trait... Which has the name method.

**Comment by autodidaddict** [comment]
You can use a constant yourself internally, but the trait is the contract between provider and host, and traits don't support constants.

**Comment by rylev** [comment]
Hmm... with associated constants (not associated types), this should be possible. Traits do support constants. https://doc.rust-lang.org/nightly/edition-guide/rust-2018/trait-system/associated-constants.html

**Comment by autodidaddict** [comment]
Nice! I've never actually seen a trait constant in the wild before. We can definitely try and make this change, but I'll maybe want to wait until there's something else breaking to bundle it with, like a codec change. This would break all of the existing plugins.

**Comment by autodidaddict** [comment]
The capability ID should also probably be a constant rather than a function.

**Comment by rylev** [comment]
Definitely no rush. I was just curious. Here is an example of where we're using associated constants in Krustlet: https://github.com/deislabs/krustlet/blob/master/crates/kubelet/src/provider.rs#L49

**Comment by autodidaddict** [comment]
Yeah that definitely looks better and will convert next time I rip open the codec. Thanks for the issue!
